"""empty message

Revision ID: 852067ef9741
Revises: 
Create Date: 2017-05-15 01:20:02.829234

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '852067ef9741'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'event', 'user', ['last_updated_by'], ['id_user'])
    op.create_foreign_key(None, 'event', 'user', ['inserted_by'], ['id_user'])
    op.create_foreign_key(None, 'event_participation', 'event', ['id_event'], ['id_event'])
    op.create_foreign_key(None, 'event_type', 'user', ['inserted_by'], ['id_user'])
    op.create_foreign_key(None, 'file', 'user', ['last_updated_by'], ['id_user'])
    op.create_foreign_key(None, 'file', 'user', ['inserted_by'], ['id_user'])
    op.create_foreign_key(None, 'tag', 'user', ['last_updated_by'], ['id_user'])
    op.create_foreign_key(None, 'tag', 'user', ['inserted_by'], ['id_user'])
    op.create_foreign_key(None, 'user', 'user', ['inserted_by'], ['id_user'])
    op.create_foreign_key(None, 'user', 'user', ['last_updated_by'], ['id_user'])
    op.create_foreign_key(None, 'user', 'file', ['id_photo_file'], ['id_file'])
    op.create_foreign_key(None, 'user_interest', 'user', ['id_user'], ['id_user'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user_interest', type_='foreignkey')
    op.drop_constraint(None, 'user', type_='foreignkey')
    op.drop_constraint(None, 'user', type_='foreignkey')
    op.drop_constraint(None, 'user', type_='foreignkey')
    op.drop_constraint(None, 'tag', type_='foreignkey')
    op.drop_constraint(None, 'tag', type_='foreignkey')
    op.drop_constraint(None, 'file', type_='foreignkey')
    op.drop_constraint(None, 'file', type_='foreignkey')
    op.drop_constraint(None, 'event_type', type_='foreignkey')
    op.drop_constraint(None, 'event_participation', type_='foreignkey')
    op.drop_constraint(None, 'event', type_='foreignkey')
    op.drop_constraint(None, 'event', type_='foreignkey')
    # ### end Alembic commands ###
